### ISSUE TITLE
三星N9005 4.4.2 demo 跑不起来

### ISSUE THREAD

**Issue by chcdg** [ximsfei/Stark#1]
05-24 09:44:33.300 10681-10681/com.ximsfei.stark.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.ximsfei.stark.app, PID: 10681
                                                                       java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.ximsfei.stark.app/com.ximsfei.stark.app.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.ximsfei.stark.app.MainActivity" on path: DexPathList[[zip file "/data/app/com.ximsfei.stark.app-9.apk"],nativeLibraryDirectories=[/data/app-lib/com.ximsfei.stark.app-9, /vendor/lib, /system/lib]]
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2208)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2340)
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:157)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1247)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:157)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5293)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:515)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
                                                                           at dalvik.system.NativeStart.main(Native Method)
                                                                        Caused by: java.lang.ClassNotFoundException: Didn't find class "com.ximsfei.stark.app.MainActivity" on path: DexPathList[[zip file "/data/app/com.ximsfei.stark.app-9.apk"],nativeLibraryDirectories=[/data/app-lib/com.ximsfei.stark.app-9, /vendor/lib, /system/lib]]
                                                                           at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:67)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                                           at android.app.Instrumentation.newActivity(Instrumentation.java:1079)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2199)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2340) 
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:157) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1247) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:157) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5293) 
                                                                           at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081) 
                                                                           at dalvik.system.NativeStart.main(Native Method) 
05-24 09:44:33.370 4755-10697/? E/android.os.Debug: !@sDumpstate is still running
05-24 09:44:33.490 10229-10431/? E/dalvikvm: Could not find class 'android.app.usage.UsageStatsManager', referenced from method tcs.ada.queryUsageStats
05-24 09:44:43.130 4755-5027/? E/WindowManager: Starting window AppWindowToken{47c7f458 token=Token{43de8768 ActivityRecord{42ae62a8 u0 com.ximsfei.stark.app/.MainActivity t81}}} timed out
05-24 09:44:44.360 10229-10229/? E/ViewRootImpl: Attempting to destroy the window while drawing!
                                                   window=android.view.ViewRootImpl@4302b058, title=

**Comment by ximsfei** [comment]
demo里开启了MultiDex，Application中没有调`MultiDex.install(this)`。
