### ISSUE TITLE
到了最后一步，点击recreate报错

### ISSUE THREAD

**Issue by ujffdi** [ximsfei/Stark#12]
1:国行三星s10+，Android P
2:跑demo代码，遵循使用教程
3:在魅族 m2 note上能成功，三星不行
还需要什么信息我可以提供
日志如下：
Process: com.ximsfei.stark.app, PID: 16193
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ximsfei.stark.app/com.ximsfei.stark.app.MainActivity}: android.content.res.Resources$NotFoundException: Drawable com.ximsfei.stark.app:mipmap/ic_launcher with resource ID #0x7f050000
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3107)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3250)
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5033)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4942)
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:59)
        at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:4992)
        at android.app.ActivityThread.access$3300(ActivityThread.java:236)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1957)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7032)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: android.content.res.Resources$NotFoundException: Drawable com.ximsfei.stark.app:mipmap/ic_launcher with resource ID #0x7f050000
     Caused by: android.content.res.Resources$NotFoundException: File res/mipmap-anydpi-v26/ic_launcher.xml from drawable resource ID #0x7f050000
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:898)
        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:677)
        at android.content.res.Resources.getDrawableForDensity(Resources.java:903)
        at android.content.res.Resources.getDrawable(Resources.java:842)
        at android.content.Context.getDrawable(Context.java:628)
        at com.android.internal.widget.ActionBarView.setIcon(ActionBarView.java:679)
        at com.android.internal.widget.ActionBarOverlayLayout.setIcon(ActionBarOverlayLayout.java:752)
        at com.android.internal.policy.PhoneWindow.setDefaultIcon(PhoneWindow.java:1796)
        at android.app.Activity.initWindowDecorActionBar(Activity.java:2844)
        at android.app.Activity.setContentView(Activity.java:2859)
        at com.ximsfei.stark.app.MainActivity.onCreate(MainActivity.java:219)
        at android.app.Activity.performCreate(Activity.java:7327)
        at android.app.Activity.performCreate(Activity.java:7318)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3087)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3250)
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5033)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4942)
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:59)
        at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:4992)
        at android.app.ActivityThread.access$3300(ActivityThread.java:236)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1957)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7032)
2019-08-08 14:52:23.919 16193-16193/com.ximsfei.stark.app E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: android.content.res.Resources$NotFoundException: Drawable (missing name) with resource ID #0x7f020002
     Caused by: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f020002
        at android.content.res.ResourcesImpl.getResourceName(ResourcesImpl.java:267)
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:831)
        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:677)
        at android.content.res.Resources.loadDrawable(Resources.java:912)
        at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:955)
        at android.graphics.drawable.AdaptiveIconDrawable.updateLayerFromTypedArray(AdaptiveIconDrawable.java:517)
        at android.graphics.drawable.AdaptiveIconDrawable.inflateLayers(AdaptiveIconDrawable.java:481)
        at android.graphics.drawable.AdaptiveIconDrawable.inflate(AdaptiveIconDrawable.java:230)
        at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:146)
        at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1359)
        at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1318)
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:879)
        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:677)
        at android.content.res.Resources.getDrawableForDensity(Resources.java:903)
        at android.content.res.Resources.getDrawable(Resources.java:842)
        at android.content.Context.getDrawable(Context.java:628)
        at com.android.internal.widget.ActionBarView.setIcon(ActionBarView.java:679)
        at com.android.internal.widget.ActionBarOverlayLayout.setIcon(ActionBarOverlayLayout.java:752)
        at com.android.internal.policy.PhoneWindow.setDefaultIcon(PhoneWindow.java:1796)
        at android.app.Activity.initWindowDecorActionBar(Activity.java:2844)
        at android.app.Activity.setContentView(Activity.java:2859)
        at com.ximsfei.stark.app.MainActivity.onCreate(MainActivity.java:219)
        at android.app.Activity.performCreate(Activity.java:7327)
        at android.app.Activity.performCreate(Activity.java:7318)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3087)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3250)
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5033)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4942)
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:59)
        at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:4992)
        at android.app.ActivityThread.access$3300(ActivityThread.java:236)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1957)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7032)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by ximsfei** [comment]
已修复
