### ISSUE TITLE
stark-sample 按照文档第二次打包补丁，修复不成功

### ISSUE THREAD

**Issue by kehongwei** [ximsfei/Stark#9]
第二次点applyPatch时，fix.apk所在文件夹出现merged.apk。修复失败，修复成功后应该是不存在的

**Comment by ximsfei** [comment]
资源修复会合并apk和补丁文件，有一个临时文件merged.apk，修复成功后会删除该文件。没有删除该文件，说明存在问题，可以贴一下具体的日志。

**Comment by kehongwei** [comment]
09-12 10:24:43.779 5711-5711/com.ximsfei.stark.app D/ViewRootImpl@5d632dc[MainActivity]: ViewPostImeInputStage processPointer 1
09-12 10:24:43.847 5711-5727/com.ximsfei.stark.app W/System.err: java.util.zip.ZipException: duplicate entry: stark.properties
09-12 10:24:43.848 5711-5727/com.ximsfei.stark.app W/System.err:     at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:216)
        at com.ximsfei.stark.core.util.ZipUtils.writeEntry(ZipUtils.java:260)
        at com.ximsfei.stark.core.Stark.applyPatch(Stark.java:349)
        at com.ximsfei.stark.core.Stark$1.run(Stark.java:380)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)
第一次修复成功，再次打补丁包就到这错误了 我也去研究下。难道和properties有关？  @ximsfei

**Comment by kehongwei** [comment]
有个问题想请教下大神   build.gradle文件里  classpath 'com.ximsfei:stark-gradle:0.0.4'  这句话能替换本地的依赖吗 我想调试方便 ？
